/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_whut_mc_server_core_util_ResolveUtil */

#ifndef _Included_org_whut_mc_server_core_util_ResolveUtil
#define _Included_org_whut_mc_server_core_util_ResolveUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_whut_mc_server_core_util_ResolveUtil
 * Method:    resolveLanyanOpenBB
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_whut_mc_server_core_util_ResolveUtil_resolveLanyanOpenBB
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
